;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<ImGui_655921752_Default>>>;;;
[Window][IMU Sensors]
Pos=0,0
Size=838,580
Collapsed=0
DockId=0x00000003,0

[Window][PID Output]
Pos=840,0
Size=560,580
Collapsed=0
DockId=0x00000004,0

[Window][Connection]
Pos=0,582
Size=489,249
Collapsed=0
DockId=0x00000005,0

[Window][PID Tuning]
Pos=491,582
Size=909,249
Collapsed=0
DockId=0x00000006,0

[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][StatusBar]
Pos=0,830
Size=1400,32
Collapsed=0

[Window][Motor Control]
Pos=491,582
Size=909,249
Collapsed=0
DockId=0x00000006,1

[Docking][Data]
DockSpace     ID=0xAFC85805 Window=0x079D3A04 Pos=14,409 Size=1400,831 Split=Y
  DockNode    ID=0x00000001 Parent=0xAFC85805 SizeRef=1400,580 Split=X
    DockNode  ID=0x00000003 Parent=0x00000001 SizeRef=838,580 CentralNode=1 Selected=0xA6831F8F
    DockNode  ID=0x00000004 Parent=0x00000001 SizeRef=560,580 Selected=0x44AF2A01
  DockNode    ID=0x00000002 Parent=0xAFC85805 SizeRef=1400,249 Split=X
    DockNode  ID=0x00000005 Parent=0x00000002 SizeRef=489,249 Selected=0x44C22849
    DockNode  ID=0x00000006 Parent=0x00000002 SizeRef=909,249 Selected=0x6A3103CC

;;;<<<Layout_655921752_Default>>>;;;
[Visibility]
1683099963_IMU_Sensors=true
2549635660_Motor_Control=true
3076503521_PID_Output=true
355191729_Connection=true
4213496394_PID_Tuning=true
;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=true
ShowFps=false
[Theme]
Name=DarculaDarker
;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{"BottomRightSpace":6,"BottomSpace":5,"MainDockSpace":2949142533,"RightSpace":4}}
